reddit_app/urls.py
from django.urls import path, include
from . import views
from .api import PostList, PostDetail

app_name = "reddit_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("change_status", views.change_status, name="change_status"),
    path("delete_post", views.delete_post, name="delete_post"),
    path('api/v1/', PostList.as_view()),
    path('api/v1/<int:pk>/', PostDetail.as_view()),
    path('api/v1/rest-auth/', include('rest_auth.urls')),
]

reddit_clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('reddit_app.urls')),
    path('accounts/', include('user_app.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name="logout"),
    path('request_password_reset/', views.request_password_reset,
         name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('delete_account/', views.delete_account, name='delete_account'),
]

ipfilter_middleware/models.py
from django.db import models

# Create your models here.

reddit_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from secrets import token_urlsafe


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=200)
    created_post_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.title} - {self.text} - {self.created_post_date}"

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

ipfilter_middleware/views.py
from django.shortcuts import render

# Create your views here.

reddit_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Post


@login_required
def index(request):
    if request.method == "POST":
        title = request.POST["title"]
        text = request.POST["text"]
        post = Post()
        post.title = title
        post.text = text
        post.save()

    posts = Post.objects.filter(user=request.user)
    context = {
        'posts': posts,
        'user': request.user
    }

    return render(request, 'reddit_app/index.html', context)


@login_required
def change_status(request):
    pk = request.POST["pk"]
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        title = request.POST["title_update"]
        post.title = title
        text = request.POST["text_update"]
        post.text = text
    post.save()

    return HttpResponseRedirect(reverse('reddit_app:index'))


@login_required
def delete_post(request):
    pk = request.POST["pk"]
    post = get_object_or_404(Post, pk=pk)
    post.delete()

    return HttpResponseRedirect(reverse('reddit_app:index'))

user_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(
            request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('reddit_app:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'user_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'user_app/login.html')


def request_password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            print(prr)
            return HttpResponseRedirect(reverse('user_app:password_reset'))

    return render(request, 'user_app/request_password_reset.html')


def password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except:
                print("Invalid password reset attempt.")
                return render(request, 'user_app/password_reset.html')

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('user_app:login'))

    return render(request, 'user_app/password_reset.html')


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
                return HttpResponseRedirect(reverse('user_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'user_app/sign_up.html', context)


@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(
                request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('user_app:login'))
            else:
                print("fail delete")

    return render(request, 'user_app/delete_account.html')

reddit_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Todo</title>
</head>
<body>
   <h1>Todo</h1>
   <p>Welcome {{ user }} - <a href="{% url 'user_app:logout' %}">Log out</a> - <a href="{% url 'user_app:delete_account' %}">Delete Account</a></p>
      {% block content %}
      {% endblock %}
      {% block footer %}
      {% endblock %}
</body>
</html>

reddit_app/templates/reddit_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static 'reddit_app/reddit_app.css' %}" media="screen"/>
    <title>Post</title>
</head>

<body>
    <h1>Posts</h1>
    <p>Welcome {{ user }} - <a href="{% url 'user_app:logout' %}">Log out</a> - <a href="{% url 'user_app:delete_account' %}">Delete Account</a></p>
    <ul>
        {% for post in posts %}
        <li>
            <form action="{% url 'reddit_app:change_status'%}" method="POST">
                {% csrf_token %}
                <h1>{{ post.title }}</h1>
                <p>{{ post.text }}</p>
                <input type="text" name="title_update" placeholder="Update title">
                <input type="text" name="text_update" placeholder="Update text">
                <button>Update</button>
                <button formaction="{% url 'reddit_app:delete_post' %}">Delete post</button>
                <input type="hidden" name="pk" value="{{ post.pk }}">
                <hr />
            </form>
        </li>
        {% endfor %}
    </ul>
    <hr />
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Insert your post title">
        <input type="text" name="text" placeholder="Insert your post desc">
        <button>Create a post</button>
    </form>

</body>

</html>

user_app/templates/user_app/delete_account.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Delete Account</title>
</head>
<body>
   <h1>Delete Account</h1>
   <hr />
   <form action="{% url 'user_app:delete_account'%}" method="POST">
      {% csrf_token %}
      <input type="password" name="password" placeholder="Password">
      <br />
      <input type="text" name="confirm_deletion" placeholder="TYPE DELETE">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

user_app/templates/user_app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
</head>

<body>
   <h1>Login</h1>
   <a href="{% url 'user_app:sign_up' %}">Sign Up</a>
   <hr />
   <form action="{% url 'user_app:login' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="password" name="password" placeholder="Password">
      <button>Login</button>
   </form>
   <hr />
   {% if error %}
   {{ error }}
   {% endif %}
   <a href="{% url 'user_app:request_password_reset' %}">Request Password Reset</a>
</body>

</html>

user_app/templates/user_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Reset Password</title>
</head>
<body>
   <h1>Reset Password</h1>
   <hr />
   <form action="{% url 'user_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name">
      <br />
      <input type="password" name="password" placeholder="New Password">
      <br />
      <input type="password" name="confirm_password" placeholder="Repeat New Password">
      <br />
      <input type="text" name="token" placeholder="Token">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

user_app/templates/user_app/request_password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Request Password Reset</title>
</head>
<body>
   <h1>Request Password Reset</h1>
   <hr />
      <form action="{% url 'user_app:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name">
            <br />
            <input type="email" name="email" placeholder="Email Address">
            <br />
            <button>Submit</button>
      </form>
   <hr />
</body>
</html>

user_app/templates/user_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <hr />
   <form action="{% url 'user_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="email" name="email" placeholder="Email Address">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <button>Sign Up</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>